import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import type { ReactNode } from 'react';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Toaster } from '@/components/ui/sonner';
import {
  Home,
  LogOut,
  MessageSquare,
  Plus,
  Search,
  Settings,
  User,
  Users,
} from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import Link from 'next/link';
import { NavItem } from '@/components/layout/nav-item';
import { ThemeToggle } from '@/components/theme-toggle';
import { getSession } from '@/lib/session';
import { LoginModal } from '@/components/auth/login-modal';
import { signOut } from '@/lib/actions/auth';
import { getUser, getUserProfile } from '@/lib/queries';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function MainLayout({ children }: { children: ReactNode }) {
  const session = await getSession();
  const user = session ? await getUser() : null;
  const userProfile = user ? await getUserProfile(user.id) : null;



  return (
    <div className="flex min-h-screen justify-center bg-background">
      <header className="sticky top-0 left-0 flex h-screen w-20 lg:w-64">
        <div className="flex h-full flex-1 flex-col items-center justify-between overflow-y-auto px-1 py-1 lg:px-3">
          <div className="flex w-full flex-col items-center lg:items-start">
            <Button
              variant="ghost"
              className="mb-3 flex size-16 items-center justify-center rounded-full p-0 hover:bg-transparent lg:w-full lg:justify-between lg:px-3 dark:hover:bg-transparent"
              asChild
            >
              <Link href="/">
                <div className="flex items-center gap-2">
                  <Users className="size-7 text-primary" />
                  <h1 className="hidden font-black text-xl lg:block">LFG</h1>
                </div>
              </Link>
            </Button>

            <nav className="flex w-full flex-col items-center gap-1">
              <NavItem href="/">
                <Home className="size-7" />
                <span className="hidden lg:block">Home</span>
              </NavItem>
              <NavItem href="/webo">
                <MessageSquare className="size-7" />
                <span className="hidden lg:block">Webo</span>
              </NavItem>
              <NavItem href="/groups/in-progress">
                <Users className="size-7" />
                <span className="hidden lg:block">Groups</span>
              </NavItem>
              <NavItem href="/search">
                <Search className="size-7" />
                <span className="hidden lg:block">Search</span>
              </NavItem>
              <NavItem href="/profile">
                <User className="size-7" />
                <span className="hidden lg:block">Profile</span>
              </NavItem>
            </nav>

            <Button
              className="mt-3 size-14 items-center justify-center gap-0 rounded-full p-0 text-md has-[>svg]:px-0 lg:h-12 lg:w-full lg:gap-2 lg:px-4 lg:py-3 lg:has-[>svg]:px-4"
              asChild
            >
              <Link href="/create-group">
                <Plus className="block size-6 lg:hidden" />
                <span className="hidden lg:block">Create Group</span>
              </Link>
            </Button>
          </div>

          {session ? (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  className="my-3 flex size-14 items-center justify-center gap-0 rounded-full p-0 has-[>svg]:px-0 lg:h-fit lg:w-full lg:justify-between lg:gap-2 lg:px-2 lg:py-2 lg:has-[>svg]:px-2"
                >
                  <div className="flex items-center gap-2">
                    <Avatar className="size-14">
                      <AvatarImage
                        src={userProfile?.icon || "https://github.com/shadcn.png"}
                        alt={userProfile?.name || "User"}
                      />
                      <AvatarFallback>
                        {userProfile?.name?.charAt(0) || "U"}
                      </AvatarFallback>
                    </Avatar>
                    <div className="hidden lg:block">
                      <p className="font-semibold text-base">{userProfile?.name || "User"}</p>
                      <p className="text-muted-foreground text-sm">@{userProfile?.userName || "username"}</p>
                    </div>
                  </div>
                  <Settings className="mr-4 hidden size-4 lg:block" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>
                  <Settings className="mr-2 size-4" />
                  <span>Settings</span>
                </DropdownMenuItem>
                <ThemeToggle />
                <DropdownMenuSeparator />
                <form action={signOut}>
                  <DropdownMenuItem asChild>
                    <button type="submit" className="w-full">
                      <LogOut className="mr-2 size-4" />
                      <span>Log out</span>
                    </button>
                  </DropdownMenuItem>
                </form>
              </DropdownMenuContent>
            </DropdownMenu>
          ) : (
            <LoginModal />
          )}
        </div>
        <Separator orientation="vertical" />
      </header>
      <main className="min-h-screen max-w-5xl flex-1">{children}</main>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>{children}</MainLayout>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
