import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';
import type { ReactNode } from 'react';
import './globals.css';
import { LoginModalWrapper } from '@/components/auth/login-modal-wrapper';
import { NavItem } from '@/components/layout/nav-item';
import { UserProfile } from '@/components/layout/user-profile';
import { ThemeProvider } from '@/components/theme-provider';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Toaster } from '@/components/ui/sonner';
import { getSession } from '@/lib/session';
import { Home, MessageSquare, Plus, Search, User, Users } from 'lucide-react';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function MainLayout({ children }: { children: ReactNode }) {
  const session = await getSession();
  return (
    <div className="flex min-h-screen justify-center bg-background">
      <header className="sticky top-0 left-0 flex h-screen w-20 lg:w-64">
        <div className="flex h-full flex-1 flex-col items-center justify-between overflow-y-auto px-1 py-1 lg:px-3">
          <div className="flex w-full flex-col items-center px-2 lg:items-start">
            <Button
              variant="ghost"
              className="mb-3 flex size-16 items-center justify-center rounded-full p-0 hover:bg-transparent lg:w-full lg:justify-between lg:px-3 dark:hover:bg-transparent"
              asChild
            >
              <Link href="/">
                <div className="flex items-center gap-2 pl-0 lg:pl-2">
                  <Users className="size-7 text-primary" />
                  <h1 className="hidden font-black text-xl lg:block">LFG</h1>
                </div>
              </Link>
            </Button>

            <nav className="flex w-full flex-col items-center gap-1">
              <NavItem href="/">
                <Home className="size-7" />
                <span className="hidden lg:block">Home</span>
              </NavItem>
              <NavItem href="/webo">
                <MessageSquare className="size-7" />
                <span className="hidden lg:block">Webo</span>
              </NavItem>
              {session && (
                <NavItem href="/groups/in-progress">
                  <Users className="size-7" />
                  <span className="hidden lg:block">Groups</span>
                </NavItem>
              )}
              <NavItem href="/search">
                <Search className="size-7" />
                <span className="hidden lg:block">Search</span>
              </NavItem>
              {session && (
                <NavItem href="/profile">
                  <User className="size-7" />
                  <span className="hidden lg:block">Profile</span>
                </NavItem>
              )}
            </nav>

            <Button
              className="mt-3 size-10 items-center justify-center gap-0 rounded-full p-0 text-md has-[>svg]:px-0 lg:h-12 lg:w-full lg:gap-2 lg:px-4 lg:py-3 lg:has-[>svg]:px-4"
              asChild
            >
              {session && (
                <Link href="/create-group">
                  <Plus className="block size-6 lg:hidden" />
                  <span className="hidden lg:block">Create Group</span>
                </Link>
              )}
            </Button>
          </div>

          {session ? (
            <Suspense
              fallback={
                <div className="h-14 w-14 animate-pulse rounded-full bg-muted" />
              }
            >
              <UserProfile />
            </Suspense>
          ) : (
            <LoginModalWrapper />
          )}
        </div>
        <Separator orientation="vertical" />
      </header>
      <main className="min-h-screen max-w-5xl flex-1">{children}</main>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>{children}</MainLayout>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
